apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      namespace: nsolid
      labels:
        app: storage
      name: storage
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: storage
        spec:
          containers:
          - image: nodesource/nsolid-storage:boron-2.0.1
            name: storage
            env:
            - name: NSOLID_STORAGE_NOTIFICATION_CONSOLE_URL
              value: http://console:3000
            - name: NSOLID_STORAGE_DATA_DIR
              value: /var/lib/nsolid/storage/data
            - name: NSOLID_STORAGE_LOGS_INFLUX
              value: /var/lib/nsolid/storage/influxdb.log
            ports:
            - containerPort: 4000
              name: api
            - containerPort: 9001
              name: command
            - containerPort: 9002
              name: data
            - containerPort: 9003
              name: bulk
            readinessProbe:
              httpGet:
                path: /api/v1/license-info
                port: 4000
                scheme: HTTPS
              initialDelaySeconds: 4
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            livenessProbe:
              httpGet:
                path: /api/v1/license-info
                port: 4000
                scheme: HTTPS
              initialDelaySeconds: 10
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      namespace: nsolid
      name: console
      labels:
        app: console
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: console
        spec:
          containers:
            - name: console
              image: nodesource/nsolid-console:boron-2.0.1
              env:
              - name: NSOLID_CONSOLE_STORAGE_URL
                value: https://storage:4000
              ports:
                - containerPort: 3000
                  name: console
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 1
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 1
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      namespace: nsolid
      labels:
        app: nginx-secure-proxy
      name: nginx-secure-proxy
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx-secure-proxy
        spec:
          containers:
          - image: nodesource/nsolid-nginx:stable
            imagePullPolicy: Always
            name: nginx-secure-proxy
            ports:
            - containerPort: 10080
              protocol: TCP
            - containerPort: 10443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/nginx/ssl/
              name: nginx-tls
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
          restartPolicy: Always
          volumes:
          - name: nginx-tls
            secret:
              secretName: nginx-tls
          - name: nginx-config
            configMap:
              name: nginx-config