apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: DeploymentList
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: console
      name: console
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: console
        spec:
          securityContext:
            fsGroup: 16753
          containers:
          - image: nodesource/nsolid-console:carbon-latest
            name: console
            env:
            - name: NSOLID_CONSOLE_DATA_DIR
              value: /var/lib/nsolid/console/data
            - name: NSOLID_CONSOLE_LOGS_INFLUX
              value: /var/lib/nsolid/console/influxdb.log
            ports:
            - containerPort: 9001
              name: command
            - containerPort: 9002
              name: data
            - containerPort: 9003
              name: bulk
            - containerPort: 6753
              name: console
            volumeMounts:
            - name: nsolid-console
              mountPath: /var/lib/nsolid
          volumes:
          - name: nsolid-console
            persistentVolumeClaim:
              claimName: nsolid-console
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: nginx-secure-proxy
      name: nginx-secure-proxy
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx-secure-proxy
        spec:
          containers:
          - image: nodesource/nsolid-nginx:stable
            imagePullPolicy: Always
            name: nginx-secure-proxy
            ports:
            - containerPort: 10080
              protocol: TCP
            - containerPort: 10443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/nginx/ssl/
              name: nginx-tls
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
          restartPolicy: Always
          volumes:
          - name: nginx-tls
            secret:
              secretName: nginx-tls
          - name: nginx-config
            configMap:
              name: nginx-config
