apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: storage
    spec:
      sessionAffinity: None
      ports:
        - name: api
          port: 4000
          targetPort: api
        - name: command
          port: 9001
          targetPort: command
        - name: data
          port: 9002
          targetPort: data
        - name: bulk
          port: 9003
          targetPort: bulk
      selector:
        app: storage
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: console
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 80
          targetPort: console
      selector:
        app: console
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nginx-secure-proxy
      labels:
        app: nginx-secure-proxy
    spec:
      type: LoadBalancer
      sessionAffinity: ClientIP
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 10080
        - name: https
          protocol: TCP
          port: 443
          targetPort: 10443
      selector:
        app: nginx-secure-proxy
